# Projet Python pour la data science

## Import et installation des packages nécessaires

On commence par importer et installer les packages nécessaires au projet. Les packages à installer sont recensés dans le fichier requirements.txt.

In [ ]:
!pip install -q -r requirements.txt

In [1]:
import os
import requests
import pandas as pd

## Récupération des données

Nous allons télécharger les données à partir de l'URL. (à expliquer mieux)

On commence par définir les variables et fonctions utiles à la récupération des données.

In [3]:
DATA_PATH = "data/maladies_chroniques.csv"
URL = "https://data.drees.solidarites-sante.gouv.fr/api/explore/v2.1/catalog/datasets/er_inegalites_maladies_chroniques/exports/csv?use_labels=true"


def download_data():
    os.makedirs("data", exist_ok=True)
    
    if not os.path.exists(DATA_PATH):
        print("Téléchargement des données...")
        r = requests.get(URL)
        with open(DATA_PATH, "wb") as f:
            f.write(r.content)
        print("Téléchargement terminé.")
    else:
        print("Fichier déjà présent.")


def load_data():
    return pd.read_csv(DATA_PATH, sep=";", encoding="utf-8")

Maintenant que l'on a tous les outils, on peut passer à la récupération des données.

In [4]:
download_data()
df = load_data()
df.head()

Fichier déjà présent.

,type,varTaux,varTauxLib,I_cat,cat,catLib,varPartition,valPartition,varGroupage,valGroupage,varPoids,poids1,poidsTot,txNonStand,txStandDir,txStandDirModBB,txStandDirModBH,txStandIndir,txStandIndirModBB,txStandIndirModBH
0,incidence,TOP_CVIC_CHR,Insuffisance cardiaque chronique,0,SUP_CV_CAT,Maladies cardioneurovasculaires,FISC_REG_S,28,NaN,NaN,POIDS_FIDELI_S,30116.961505,6.302392e+06,0.004779,0.004779,0.004521,0.005037,0.004779,0.004521,0.005037
1,incidence,TOP_PRETARD_IND,Déficience mentale,0,SUP_PSYPAT_CAT,Maladies psychiatriques,FISC_REG_S,28,NaN,NaN,POIDS_FIDELI_S,1309.430271,6.349002e+06,0.000206,0.000206,0.000150,0.000263,0.000206,0.000150,0.000263
2,incidence,TOP_RTRANS_CHR,Suivi de transplantation rénale,0,SUP_RIRCT_CAT,Insuffisance rénale chronique terminale,FISC_REG_S,28,FISC_NIVVIEM_E2015_S_moy_10,1,POIDS_FIDELI_S,0.000000,5.294220e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,incidence,TOP_CVTRRYC_IND,Troubles du rythme ou de la conduction cardiaque,0,SUP_CV_CAT,Maladies cardioneurovasculaires,FISC_REG_S,28,FISC_NIVVIEM_E2015_S_moy_10,2,POIDS_FIDELI_S,6959.005587,6.266976e+05,0.011104,0.011745,0.010400,0.013090,0.011888,0.010576,0.013201
4,incidence,TOP_IRHEMOP_IND,Hémophilie ou troubles de l'hémostase graves,0,SUP_INFRARVIH_CAT,Maladies inflammatoires ou rares ou VIH ou SIDA,FISC_REG_S,28,FISC_NIVVIEM_E2015_S_moy_10,2,POIDS_FIDELI_S,92.865604,6.438119e+05,0.000144,0.000147,-0.000005,0.000300,0.000154,-0.000004,0.000312

On peut le faire par API (c'est mieux je pense, les deux donnent la même chose à la fin donc il faut choisir la meilleure méthode).

In [5]:
url = "https://www.data.gouv.fr/api/1/datasets/inegalites-sociales-face-aux-maladies-chroniques-er-1243/"

response = requests.get(url)
data = response.json()

print(data.keys())

dict_keys(['access_audiences', 'access_type', 'access_type_reason', 'access_type_reason_category', 'acronym', 'archived', 'authorization_request_url', 'badges', 'contact_points', 'created_at', 'deleted', 'description', 'description_short', 'extras', 'featured', 'frequency', 'frequency_date', 'harvest', 'id', 'internal', 'last_modified', 'last_update', 'license', 'metrics', 'organization', 'owner', 'page', 'permissions', 'private', 'quality', 'resources', 'schema', 'slug', 'spatial', 'tags', 'temporal_coverage', 'title', 'uri'])

In [6]:
resources = data["resources"]

for r in resources:
    print(r["title"], r["url"])

er_inegalites_maladies_chroniques.csv https://data.drees.solidarites-sante.gouv.fr/api/explore/v2.1/catalog/datasets/er_inegalites_maladies_chroniques/exports/csv?use_labels=true
er_inegalites_maladies_chroniques.json https://data.drees.solidarites-sante.gouv.fr/api/explore/v2.1/catalog/datasets/er_inegalites_maladies_chroniques/exports/json
ex_analyse_maladies_chroniques.R https://data.drees.solidarites-sante.gouv.fr/api/v2/catalog/datasets/er_inegalites_maladies_chroniques/alternative_exports/ex_analyse_maladies_chroniques_r
libelles_er1243.xlsx https://data.drees.solidarites-sante.gouv.fr/api/v2/catalog/datasets/er_inegalites_maladies_chroniques/alternative_exports/libelles_er1243_xlsx

In [8]:
csv_url = resources[0]["url"]  # adapte si plusieurs fichiers
df = pd.read_csv(csv_url, sep=";")

df.head()

,type,varTaux,varTauxLib,I_cat,cat,catLib,varPartition,valPartition,varGroupage,valGroupage,varPoids,poids1,poidsTot,txNonStand,txStandDir,txStandDirModBB,txStandDirModBH,txStandIndir,txStandIndirModBB,txStandIndirModBH
0,incidence,TOP_CVIC_CHR,Insuffisance cardiaque chronique,0,SUP_CV_CAT,Maladies cardioneurovasculaires,FISC_REG_S,28,NaN,NaN,POIDS_FIDELI_S,30116.961505,6.302392e+06,0.004779,0.004779,0.004521,0.005037,0.004779,0.004521,0.005037
1,incidence,TOP_PRETARD_IND,Déficience mentale,0,SUP_PSYPAT_CAT,Maladies psychiatriques,FISC_REG_S,28,NaN,NaN,POIDS_FIDELI_S,1309.430271,6.349002e+06,0.000206,0.000206,0.000150,0.000263,0.000206,0.000150,0.000263
2,incidence,TOP_RTRANS_CHR,Suivi de transplantation rénale,0,SUP_RIRCT_CAT,Insuffisance rénale chronique terminale,FISC_REG_S,28,FISC_NIVVIEM_E2015_S_moy_10,1,POIDS_FIDELI_S,0.000000,5.294220e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,incidence,TOP_CVTRRYC_IND,Troubles du rythme ou de la conduction cardiaque,0,SUP_CV_CAT,Maladies cardioneurovasculaires,FISC_REG_S,28,FISC_NIVVIEM_E2015_S_moy_10,2,POIDS_FIDELI_S,6959.005587,6.266976e+05,0.011104,0.011745,0.010400,0.013090,0.011888,0.010576,0.013201
4,incidence,TOP_IRHEMOP_IND,Hémophilie ou troubles de l'hémostase graves,0,SUP_INFRARVIH_CAT,Maladies inflammatoires ou rares ou VIH ou SIDA,FISC_REG_S,28,FISC_NIVVIEM_E2015_S_moy_10,2,POIDS_FIDELI_S,92.865604,6.438119e+05,0.000144,0.000147,-0.000005,0.000300,0.000154,-0.000004,0.000312

## Visualisation

## Modélisation